// <auto-generated />
using aoe.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace aoe.Migrations
{
    [DbContext(typeof(AoeDbContext))]
    [Migration("20260523134500_FixStudentAnswersTable")]
    partial class FixStudentAnswersTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
